# Generated by Django 2.0.3 on 2018-04-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
