# Generated by Django 2.0.3 on 2018-04-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20180402_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
