# Generated by Django 2.0.3 on 2018-04-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20180404_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='locations.Location'),
        ),
    ]
