# Generated by Django 2.0.3 on 2018-04-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20180408_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='lat',
            field=models.FloatField(blank=True, default=59.955413),
        ),
        migrations.AddField(
            model_name='review',
            name='lng',
            field=models.FloatField(blank=True, default=30.337),
        ),
    ]
