# Generated by Django 2.0.3 on 2018-04-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20180408_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.ForeignKey(db_column='location', on_delete=django.db.models.deletion.DO_NOTHING, to='locations.Location'),
        ),
    ]
