# Generated by Django 2.0.3 on 2018-04-16 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0009_auto_20180409_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='review',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='review_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
