# Generated by Django 2.0.3 on 2018-04-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20180409_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='upvotes',
            field=models.CharField(max_length=120),
        ),
    ]
