# Generated by Django 2.0.3 on 2018-04-16 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20180416_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='downvotes',
        ),
        migrations.AlterField(
            model_name='review',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='review_downvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
