# Generated by Django 2.0.3 on 2018-04-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20180413_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
