# Generated by Django 2.0.3 on 2018-04-16 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0011_auto_20180416_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='review_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='review_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
