# Generated by Django 2.0.3 on 2018-04-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20180413_1457'),
        ('reviews', '0012_auto_20180416_1407'),
    ]

    operations = [
    ]
